### ISSUE TITLE
error checkpoints/cm.lib

### ISSUE THREAD

**Issue by SmallWangs** [zhangqian6/deepnodezq#1]
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Traceback (most recent call last):
  File "c:\Users\wang\Downloads\deepnodezq-mas\main.py", line 30, in <module>
    main()
  File "c:\Users\wang\Downloads\deepnodezq-mas\main.py", line 21, in main
    watermark = process(dress)
                ^^^^^^^^^^^^^^
  File "c:\Users\wang\Downloads\deepnodezq-mas\run.py", line 115, in process
    model.initialize(opt)
  File "c:\Users\wang\Downloads\deepnodezq-mas\gan.py", line 69, in initialize
    self.__load_network(self.netG)
  File "c:\Users\wang\Downloads\deepnodezq-mas\gan.py", line 89, in __load_network
    network.load_state_dict(torch.load(save_path))
                            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\serialization.py", line 444, in _open_file_like

    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wang\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\serialization.py", line 425, in __init__       
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

**Comment by iwbimb** [comment]
Me, too. There's no pre-training model

**Comment by ForAurie** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/cm.lib'

**Comment by cangyan12138** [comment]
有人指导预训练模型在哪里下载吗

**Comment by ForAurie** [comment]
> 有人指导预训练模型在哪里下载吗

彪起中文了？早知道我也不装了。。。
